# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('multi_language', models.BooleanField(default=False)),
                ('skill_level', models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=3)),
                ('link_url', models.URLField()),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('multi_language', models.BooleanField(default=False)),
                ('skill_level', models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=3)),
                ('playlist_id', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('multi_language', models.BooleanField(default=False)),
                ('skill_level', models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=3)),
                ('video_id', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Domain')),
                ('language', models.ManyToManyField(to='courses.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.ManyToManyField(to='courses.Technology'),
        ),
        migrations.AddField(
            model_name='course_link',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Domain'),
        ),
        migrations.AddField(
            model_name='course_link',
            name='language',
            field=models.ManyToManyField(to='courses.Technology'),
        ),
    ]
