# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_link',
            name='skill_level',
            field=models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='skill_level',
            field=models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='skill_level',
            field=models.CharField(choices=[('SKILL_BEGINNER', 'Beginners'), ('SKILL_INTERMEDIATE', 'Intermediate'), ('SKILL_ADVANCE', 'Advance')], max_length=20),
        ),
    ]
